version: "3.3"

services:
  web:
    image: trevor5f/skypro_hw_26
    build: .
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name

