###
GET http://127.0.0.1:8000/
Accept: application/json

###
GET http://127.0.0.1:8000/cat/
Accept: application/json

###
GET http://127.0.0.1:8000/ad/
Accept: application/json

###
POST http://127.0.0.1:8000/cat/
Accept: application/json
Content-Type: application/json

{
  "name": "Новая категория"
}

###
POST http://127.0.0.1:8000/ad/
Accept: application/json
Content-Type: application/json

{
  "name": "Новая категория"
}
